### ISSUE TITLE
Header With logo in middle 

### ISSUE THREAD

**Issue by kostas2231** [mantinedev/ui.mantine.dev#10]
Hello , I am new to React and I am trying to use the Header with logo in middle. I am familliar with React Native , but React is a whole different story. I installed all the needed dependecies and I created a Navbar.tsx file. Added the code and so. I tried to use it but i get an error regarding links and nothing shows up . What is the correct usage? I even tried with dummy data creating a variable and adding the links from the example , but still no luck. Sorry if my question makes no sense feel free to delete it if so.
Thanks in advance!

**Comment by kostas2231** [comment]
Hello again, I also forgot to mention that my goal is to build a single page website and in links I would like to have sections . Clicking the ‘About’ will scroll you to this section

**Comment by Dragonlord1005** [comment]
You need to provide them as arguments when calling it. Here is an example [Example](https://github.com/Dragonlord1005/next-boi/blob/main/components/layout.tsx)

**Comment by Dragonlord1005** [comment]
Let me know if it works

**Comment by kostas2231** [comment]
> Let me know if it works

thank you. Much appreciated it works perfectly.
