### ISSUE TITLE
"my=" attribute ?

### ISSUE THREAD

**Issue by ahetawal-p** [mantinedev/ui.mantine.dev#27]
Going over the example source code, 
https://github.com/mantinedev/ui.mantine.dev/blob/master/components/GridAsymmetrical/GridAsymmetrical.tsx#L7

I see something like this:
```
 <Container my="md">
      <Grid>
        <Grid.Col xs={4}>{child}</Grid.Col>
```

What exactly is the `my=` attribute? 
I could not find it in documentation ?

**Comment by rtivital** [comment]
https://mantine.dev/pages/basics/#components-props

**Comment by ahetawal-p** [comment]
ahh thank you !
