### ISSUE TITLE
Looks great, but where can I actually get the components?

### ISSUE THREAD

**Issue by matthewoates** [mantinedev/ui.mantine.dev#5]
Is this a new major version of `@mantine/core`? Is this being launched as a new package? The website looks mature, but I'm not seeing where these components can actually be consumed by codebases.

**Comment by rtivital** [comment]
You get full components code on the website and take full ownership over the code after that, that is all Mantine UI provides, it will never be published as npm package.

**Comment by matthewoates** [comment]
Thanks for the quick response. I appreciate open-sourcing this great work.

I'm curious about the decision to not publish this as an NPM package - I don't see why this is deviating from the pattern of publishing code as an NPM package.

**Comment by shinebayar-g** [comment]
Ah that makes sense. Thanks for the explanation.
