### ISSUE TITLE
Version 2 of @tabler/icons gives me an error.

### ISSUE THREAD

**Issue by masakinihirota** [mantinedev/ui.mantine.dev#50]
Environment
windows 10
chrome 110.0.5481.77 64bit

Repository
https://github.com/masakinihirota/mantine-admin/commit/c832c714406b0e50fef30cea8e69ba59ec2b7ce5

@tabler/icons "^2.3.0" -> "^1.107.0"
Versioned down and worked.

Navbars.
When trying to get DoubleNavbar.tsx to work

npm install @tabler/icons
to install.
However, an error occurred and it did not work.

I downgraded the version and it worked.
@tabler/icons 1.107.0

**Comment by rtivital** [comment]
Use `@tabler/icons-react` package instead

**Comment by masakinihirota** [comment]
Thank you so much.
