### ISSUE TITLE
TS2305: Module '"@mantine/core"' has no exported member 'rem'.

### ISSUE THREAD

**Issue by jeli-t** [mantinedev/ui.mantine.dev#54]
I get this error while running the following:
`import  { rem} from '@mantine/core';`

I'm using the newest versions of mantine and typescript.

**Comment by rtivital** [comment]
You must update all `@mantine/` packages to `6.0` to use rem function.

**Comment by jeli-t** [comment]
I already had updated to 6.0. I have removed and reinstalled all node_modules and it worked. Thanks for your help any way.
