### ISSUE TITLE
Build issues with components SocialButtons and TaskCard

### ISSUE THREAD

**Issue by renep16** [mantinedev/ui.mantine.dev#55]
<img width="617" alt="Captura de pantalla 2023-03-06 a la(s) 10 53 58 p  m" src="https://user-images.githubusercontent.com/50551882/223308205-f89865c4-c7b5-4e9e-8d17-2867ec264987.png">

<img width="545" alt="Captura de pantalla 2023-03-06 a la(s) 10 54 18 p  m" src="https://user-images.githubusercontent.com/50551882/223308238-77e4db63-43bb-4855-b35f-f30601567644.png">

**Comment by rtivital** [comment]
You must use latest version of `@mantine` packages and `@tabler/icons-react`
