### ISSUE TITLE
cannot find @mantine/utils in nowhere

### ISSUE THREAD

**Issue by Nipodemos** [mantinedev/ui.mantine.dev#60]
hello!
thanks for this awesome library, i'm starting to using it and i'm loving!

Just want to report something, on the example [Table with search and sort](https://ui.mantine.dev/category/tables#table-sort), it is importing a function called `keys` from the library `@mantine/utils`, but i'm not finding that library anywhere on mantine website. Could you point it out if the name changed or something like that?

Thanks in advance

**Comment by rtivital** [comment]
This package does not have documentation. You can explore its source code if you are interested.

**Comment by Nipodemos** [comment]
thanks for the reply, i'll take a look
