### ISSUE TITLE
[Help Wanted, Urgent] Tailwind CSS support.

### ISSUE THREAD

**Issue by Syed-Sheharyar** [mantinedev/ui.mantine.dev#65]
Can I use Tailwind CSS for styling as I prefer it over your default create style and theme css-in-js solution? Does it work correctly without any style overrides as Mantine now also provides unstyled components? I am wondering if I use Tailwind CSS it doesn't make style conflicts or weird behavior in different browsers. As Tailwind CSS is widely used so if you somehow allow choosing between Tailwind CSS or CSS-in-js. Your library also gets a boost in popularity resulting in more adoption. **_Consider, this as an important factor please, and answer me._** You can also come up with an unstyled version of all components which gives the flexibility to use any styling solution.

**Comment by Uzaaft** [comment]
Did you try and combine those two? It worked perfectly fine for me. :) You should put some efforts in researching the issue you're wondering, before you create an issue.

**Comment by Syed-Sheharyar** [comment]
Do you completely eliminate Mantine CSS-in-js and design all components through Tailwind? Controlling light and dark themes using Tailwind instead of Mantine CSS-in-js. It means you are saying that there are no style conflicts in any browser and weird behavior. I am asking because I will use this in an enterprise-grade project where everything should be perfect or I try other UI libraries. How do you set up Tailwind with Mantine please, provide some code.

**Comment by Uzaaft** [comment]
> Do you completely eliminate Mantine CSS-in-js and design all components through Tailwind? Controlling light and dark themes using Tailwind instead of Mantine CSS-in-js. It means you are saying that there are no style conflicts in any browser and weird behavior. I am asking because I will use this in an enterprise-grade project where everything should be perfect or I try other UI libraries. How do you set up Tailwind with Mantine please, provide some code.

Try it out yourself.
