### ISSUE TITLE
DatePickerInput or any Date component @mantine/dates shows with broken styling 

### ISSUE THREAD

**Issue by AsgharCeethirakthu** [mantinedev/ui.mantine.dev#75]
"@mantine/dates": "^7.1.7",
"@mantine/core": "^7.1.3",
"@mantine/ds": "^7.1.3",
"typescript": "^5.0.2",
"react": "^18.2.0",

![image](https://github.com/mantinedev/ui.mantine.dev/assets/72439187/fd25856a-634d-4edb-bb1c-d1ee34feeb4b)

while comparing with the demo I see some styles are missing

saw a similar case reported here as well https://stackoverflow.com/questions/77422657/mantine-datepickerinput-rendering-bug

**Comment by rtivital** [comment]
You did not import `import '@mantine/dates/styles.css';` – https://mantine.dev/dates/getting-started/#installation

**Comment by AsgharCeethirakthu** [comment]
Worked. Thank You
