### ISSUE TITLE
Is there any special meaning to using the rem function as in this sample code?

### ISSUE THREAD

**Issue by eastack** [mantinedev/ui.mantine.dev#76]
After looking at the documentation, this function seems similar to the remainder operator (%) in JS, but here it only provides one parameter. So why don't we just write the corresponding value directly instead of using the rem function? Is there some other reason for it?

[https://ui.mantine.dev/component/header-search/](url)

![image](https://github.com/mantinedev/ui.mantine.dev/assets/17524858/629ec5f4-9970-4243-a218-b2d0fbb1810d)

**Comment by rtivital** [comment]
https://mantine.dev/styles/postcss-preset/#remem-functions

**Comment by eastack** [comment]
Thank you so much for your help! I really appreciate you taking the time to help me with this. As a newbie, I don't have a good understanding of frontend engineering systems. But a question comes to my mind - if I want to use the original `rem` function in CSS, will it conflict with this feature (or can it be automatically distinguished by checking the number of arguments during preprocessing)?
