### ISSUE TITLE
How to use links

### ISSUE THREAD

**Issue by Dragonlord1005** [mantinedev/ui.mantine.dev#8]
How do I actually define what the links are for https://github.com/mantinedev/ui.mantine.dev/blob/master/components/HeaderResponsive/HeaderResponsive.tsx ?

**Comment by rtivital** [comment]
Maintainers do not provide any support for Mantine UI because we share full code of the components, and then it becomes your job to adopt it to work with your application. You can try asking your question on Discord and get help from community.

**Comment by kostas2231** [comment]
> How do I actually define what the links are for https://github.com/mantinedev/ui.mantine.dev/blob/master/components/HeaderResponsive/HeaderResponsive.tsx ?

Any updates on this please?

**Comment by Dragonlord1005** [comment]
@kostas2231 You need to provide them as arguments when calling it. Here is an example [https://github.com/Dragonlord1005/next-boi/blob/main/components/layout.tsx](Example)
