### ISSUE TITLE
Typo: Currency sign is not prefixing the value amount

### ISSUE THREAD

**Issue by fagro-vizcaino** [mantinedev/ui.mantine.dev#93]
Tiny typo, the currency sign is not prefixing the amount

https://github.com/mantinedev/ui.mantine.dev/blob/8be56fdda5b7697f7448187f1c4750a8514af16a/lib/CarouselCard/CarouselCard.tsx#L58

**Comment by fagro-vizcaino** [comment]
Hi @ryeviz 

Do you mean to use a component like `NumberFormatter` for the prefix?
Or do you mean that it's ok the way it's displayed?

<img width="456" alt="image" src="https://github.com/mantinedev/ui.mantine.dev/assets/57339071/8b9ad594-522f-4f62-aaa5-e0c9d529475a">

**Comment by ryeviz** [comment]
Hello @fagro-vizcaino
Just add the currency sign before the amount

<Text fz="xl" span fw={500} className={classes.price}>
    $397
  </Text>

**Comment by fagro-vizcaino** [comment]
Sure, that's what I did on this PR to fix that example.

https://github.com/mantinedev/ui.mantine.dev/pull/94/commits/a285bdc298c9779d72e851d58307e12cfca26a4b
